name = "mugenbatscha"
license = "MIT"
licenselink = "https://github.com/lauwarm/hugo-theme-mugenbatscha/blob/main/LICENSE"
description = "A Theme"
homepage = "https://github.com/lauwarm/hugo-theme-mugenbatscha"
tags = ["blog", "personal"]
features = ["none"]
min_version = "0.86.1"

[author]
  name = "Fabian"
  homepage = "https://mugenbatscha.me/"

# If porting an existing theme
#[original]
#  name = ""
#  homepage = ""
#  repo = ""
